better handling of canmount property
TemptorSent/beadm pull request #1
Opened 2018-07-11 16:32 UTC by mergwyn

The major change in this PR is to preserve canmount settings when manipulating BEs.  The reason for this is that a BE could contain zfs file systems just for the directory hierarchy, example <BE>/var, which should never be mounted.

I have tested this on Ubuntu 16.04 and the /bin/sh does not support the some of the substitutions eg ${ZFSMODVER//./} on line 51, so I changed the default shell to bash.

2018-08-27 08:23 UTC, TemptorSent requested changes
This script is explicitly meant to work in a minimal posix environment, such as an initrmafs, and as such depends explicitly on 'sh' semantics, which bash will conform to when invoked as 'sh'.

2018-08-27 08:26 UTC, TemptorSent requested changes
The ordering of the changing of canmount and mountpoint become important when split into two operations. canmount=noauto should be set before changing mountpoint to avoid possible problems.

2018-08-27 08:28 UTC, TemptorSent reviewed
NAK -- 'sh' is used explicitly to ensure cross-platform and minimal posix environment compatibility.

2018-08-27 08:29 UTC, TemptorSent approved these changes

2018-08-27 09:38 UTC, mergwyn commented
Sorry about the confusing changes - just checking you happy with the proposed PR (given you have approved)

2018-08-27 10:01 UTC, TemptorSent requested changes
Sorry, it seems I applied the approved to the entire changeset, not the specific revision as I intended. Please eliminate an bashisms you hit and revert to sh, as well as flipping the order for the canmount and mountpoint setting. Otherwise looks good!

2018-08-28 13:13 UTC, mergwyn commented
The commit "remove ZFSMODVER dependency on variable string substitution" fixed the issue I had with sh vs bash, so hopefully that is covered.
Re ordering: I changed the operations around on line 1170 but could not find other examples (the ordering looked correct around line 920).

2018-08-28 16:36 UTC, TemptorSent commented
Looks good except 'shell=/bin/bash' needs to be changed back to 'shell=/bin/sh'.
(sidenote - it would be nice if github actually allowed cherry-picking commits to discuss/merge in a PR, sorry for the confusion of applying statuses to the whole PR.)

2018-08-28 16:51 UTC, mergwyn commented
No problem.  I tried to explain in my comment that the commit “remove ZFSMODVER dependency on variable string substitution” changed to code so that bash was not needed and changed line 1 to /bin/sh

2018-08-28 17:08 UTC, TemptorSent commented on beadm
> +shell=/bin/bash
This needs to change back to /bin/sh

2018-08-29 08:54 UTC, TemptorSent commented
Okay, looks good - I'll go ahead and merge.
Please test the cloning with a nested canmount=on dataset to make sure it acts properly, but that's the only thing I see off-hand that could possibly cause issues for some use-cases.
Thank you for your contribution and patience!

2018-08-29 09:02 UTC, merged